// The A7 envelope golden vector (`vectors/signed/envelope.json`, generated by
// `crates/spindle-core/src/bin/gen_crypto_vectors.rs`): re-derives every step from the TEST-ONLY
// seeds — device keys, ephemeral keys, the two X25519 DHs, the session key, the nonce, the AAD —
// and checks each intermediate value byte-for-byte against the vector before decrypting,
// verifying the real signature, and round-tripping `seal`.

import { Envelope, bytesToHex, hexToBytes } from "@spindle/proto";
import { describe, expect, it } from "vitest";

import { ed25519PublicKeyFromSeed, ed25519Verify, x25519PublicKeyFromSeed, x25519SharedSecret } from "../src/backend.js";
import { deriveSessionKey, directionByte, open, seal } from "../src/envelope.js";
import { deviceFpOf } from "../src/fingerprint.js";
import { aesGcmOpen } from "../src/primitives.js";
import { loadSignedVectorFile } from "./helpers.js";

interface DeviceFixtureJson {
  sign_seed: { seed_hex: string };
  sign_pk_hex: string;
  agree_seed: { seed_hex: string };
  agree_pk_hex: string;
  eph_seed: { seed_hex: string };
  eph_pk_hex: string;
  device_fp_hex: string;
}

async function loadDeviceFixture(json: DeviceFixtureJson) {
  const signSeed = hexToBytes(json.sign_seed.seed_hex);
  const agreeSeed = hexToBytes(json.agree_seed.seed_hex);
  const ephSeed = hexToBytes(json.eph_seed.seed_hex);

  const signPk = await ed25519PublicKeyFromSeed(signSeed);
  expect(bytesToHex(signPk)).toBe(json.sign_pk_hex);

  const agreePk = await x25519PublicKeyFromSeed(agreeSeed);
  expect(bytesToHex(agreePk)).toBe(json.agree_pk_hex);

  const ephPk = await x25519PublicKeyFromSeed(ephSeed);
  expect(bytesToHex(ephPk)).toBe(json.eph_pk_hex);

  const fp = await deviceFpOf(1, signPk, agreePk);
  expect(bytesToHex(fp)).toBe(json.device_fp_hex);

  return { signSeed, signPk, agreeSeed, agreePk, ephSeed, ephPk, fp };
}

describe("envelope.json", () => {
  const doc = loadSignedVectorFile("envelope.json");

  it("re-derives the session key from the seeds", async () => {
    const a = await loadDeviceFixture(doc.device_a);
    const b = await loadDeviceFixture(doc.device_b);
    const sid = hexToBytes(doc.sid_hex);

    const ephDh = await x25519SharedSecret(a.ephSeed, b.ephPk);
    const devDh = await x25519SharedSecret(a.agreeSeed, b.agreePk);
    const sessionKey = await deriveSessionKey(ephDh, devDh, sid, a.fp, b.fp);
    expect(bytesToHex(sessionKey)).toBe(doc.session_key_hex);
  });

  it("reproduces nonce/AAD/ciphertext, decrypts, and verifies the real signature (a_to_b_first_message)", async () => {
    const a = await loadDeviceFixture(doc.device_a);
    const b = await loadDeviceFixture(doc.device_b);
    const sid = hexToBytes(doc.sid_hex);
    const sessionKey = hexToBytes(doc.session_key_hex);

    const c = doc.cases.find((x: { name: string }) => x.name === "a_to_b_first_message");

    const direction = directionByte(a.fp, b.fp);
    expect(direction).toBe(c.direction_byte);

    const env = Envelope.fromCanonicalBytes(hexToBytes(c.envelope_canonical_cbor_hex));
    const aad = Envelope.headerCanonicalBytes(env);
    expect(bytesToHex(aad)).toBe(c.aad_hex);

    const nonce = new Uint8Array(12);
    nonce[0] = direction;
    // seq = 0 for this case, so the big-endian seq bytes are already zero.
    expect(bytesToHex(nonce)).toBe(c.nonce_hex);

    expect(bytesToHex(env.ciphertext)).toBe(c.ciphertext_hex);
    const plaintext = await aesGcmOpen(sessionKey, nonce, aad, env.ciphertext);
    expect(bytesToHex(plaintext)).toBe(c.plaintext_hex);

    expect(bytesToHex(Envelope.signingInput(env))).toBe(c.signing_input_hex);
    expect(bytesToHex(env.sig)).toBe(c.signature_hex);
    const sigValid = await ed25519Verify(a.signPk, Envelope.signingInput(env), env.sig);
    expect(sigValid).toBe(true);

    // Full `open()` round-trip through this package's public API.
    const opened = await open(
      {
        sessionKey,
        pinnedSenderKey: a.signPk,
        selfFp: b.fp,
        expectedSid: sid,
        now: env.ts,
        minV: 1,
        minAlgId: 1,
        expectedKind: 1,
        senderRevoked: false,
      },
      env,
    );
    expect(bytesToHex(opened)).toBe(c.plaintext_hex);
  });

  it("seal() reproduces the vector's ciphertext/signature/canonical bytes exactly (deterministic AEAD nonce + deterministic Ed25519)", async () => {
    const a = await loadDeviceFixture(doc.device_a);
    const b = await loadDeviceFixture(doc.device_b);
    const sid = hexToBytes(doc.sid_hex);
    const sessionKey = hexToBytes(doc.session_key_hex);
    const c = doc.cases.find((x: { name: string }) => x.name === "a_to_b_first_message");

    const env = await seal({
      sessionKey,
      signSeed: a.signSeed,
      v: 1,
      algId: 1,
      fromFp: a.fp,
      toFp: b.fp,
      sid,
      kind: 1,
      seq: 0n,
      ts: BigInt(c.ts),
      ephPk: a.ephPk,
      plaintext: hexToBytes(c.plaintext_hex),
    });

    expect(bytesToHex(env.ciphertext)).toBe(c.ciphertext_hex);
    expect(bytesToHex(env.sig)).toBe(c.signature_hex);
    expect(bytesToHex(Envelope.toCanonicalBytes(env))).toBe(c.envelope_canonical_cbor_hex);
  });

  it("tampered_signature_last_byte: open() rejects with BadSignature", async () => {
    const a = await loadDeviceFixture(doc.device_a);
    const b = await loadDeviceFixture(doc.device_b);
    const sid = hexToBytes(doc.sid_hex);
    const sessionKey = hexToBytes(doc.session_key_hex);
    const c = doc.cases.find((x: { name: string }) => x.name === "tampered_signature_last_byte");

    const env = Envelope.fromCanonicalBytes(hexToBytes(c.envelope_canonical_cbor_hex));
    expect(bytesToHex(env.sig)).toBe(c.signature_hex);

    await expect(
      open(
        {
          sessionKey,
          pinnedSenderKey: a.signPk,
          selfFp: b.fp,
          expectedSid: sid,
          now: env.ts,
          minV: 1,
          minAlgId: 1,
          expectedKind: 1,
          senderRevoked: false,
        },
        env,
      ),
    ).rejects.toMatchObject({ kind: "BadSignature" });
  });
});
